In [1]:
import torch
from torch.utils.data import Dataset
import numpy as np
import torchvision
from torchvision import transforms

### Create custom Dataset

In [2]:
class MyDataset(Dataset):
  def __init__(self, transform=None):
    data = np.loadtxt('data_1.csv', delimiter=',', skiprows=1)
    self.x = torch.from_numpy(data[:, 0:2])
    self.y = torch.from_numpy(data[:, 2])
    self.transform = transform
    self.length = data.shape[0]

  def __getitem__(self, index):
    sample = self.x[index], self.y[index]
    if self.transform:
      sample = self.transform(sample)
    return sample

  def __len__(self):
    return self.length

In [3]:
ds = MyDataset()
for i in range(3):
  x, y = ds[i]
  print(x, y)

tensor([10., 20.], dtype=torch.float64) tensor(2., dtype=torch.float64)
tensor([ 5., 25.], dtype=torch.float64) tensor(1., dtype=torch.float64)
tensor([2., 7.], dtype=torch.float64) tensor(0., dtype=torch.float64)


In [4]:
len(ds)

5

### Create Tranforms

In [5]:
class TrA(object):
  def __init__(self, s=1):
    self.s = s
  
  def __call__(self, sample):
    x = sample[0]*self.s
    y = sample[1]*self.s
    sample = x, y
    return sample


In [7]:
tr1 = TrA(s=10)
ds1 = MyDataset(transform=tr1)
for i in range(3):
  x, y = ds1[i]
  print(x, y)

tensor([100., 200.], dtype=torch.float64) tensor(20., dtype=torch.float64)
tensor([ 50., 250.], dtype=torch.float64) tensor(10., dtype=torch.float64)
tensor([20., 70.], dtype=torch.float64) tensor(0., dtype=torch.float64)


### Compose Transforms

In [8]:
class TrB(object):
  
  def __call__(self, sample):
    x = sample[0] + 10
    y = sample[1]*2
    sample = x, y
    return sample

In [9]:
tr_composed = transforms.Compose([TrA(10), TrB()])
ds2 = MyDataset(transform=tr_composed)
for i in range(3):
  x, y = ds2[i]
  print(x, y)

tensor([110., 210.], dtype=torch.float64) tensor(40., dtype=torch.float64)
tensor([ 60., 260.], dtype=torch.float64) tensor(20., dtype=torch.float64)
tensor([30., 80.], dtype=torch.float64) tensor(0., dtype=torch.float64)
